name: Build Release
on:
  push:
    tags:
      - '**'
jobs:
  release:
    uses: onecx-apps/ci-quarkus/.github/workflows/build-release.yml@v1
    secrets: inherit
    with:
      helmEventTargetRepository: onecx-apps/onecx-ai
