name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "fix/[0-9]+.[0-9]+.x"

jobs:
  build:
    uses: onecx-apps/ci-quarkus/.github/workflows/build.yml@v2
    secrets: inherit
    with:
      helmEventTargetRepository: onecx-apps/onecx-ai
